/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalleryAlbumIdRouteImport } from './routes/gallery_.$albumId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryAlbumIdRoute = GalleryAlbumIdRouteImport.update({
  id: '/gallery_/$albumId',
  path: '/gallery/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/habits': typeof HabitsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/statistics': typeof StatisticsRoute
  '/templates': typeof TemplatesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/gallery/$albumId': typeof GalleryAlbumIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/habits': typeof HabitsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/statistics': typeof StatisticsRoute
  '/templates': typeof TemplatesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/gallery/$albumId': typeof GalleryAlbumIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/habits': typeof HabitsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/statistics': typeof StatisticsRoute
  '/templates': typeof TemplatesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/gallery_/$albumId': typeof GalleryAlbumIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/habits'
    | '/login'
    | '/profile'
    | '/statistics'
    | '/templates'
    | '/auth/callback'
    | '/gallery/$albumId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery'
    | '/habits'
    | '/login'
    | '/profile'
    | '/statistics'
    | '/templates'
    | '/auth/callback'
    | '/gallery/$albumId'
  id:
    | '__root__'
    | '/'
    | '/gallery'
    | '/habits'
    | '/login'
    | '/profile'
    | '/statistics'
    | '/templates'
    | '/auth/callback'
    | '/gallery_/$albumId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRoute
  HabitsRoute: typeof HabitsRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  StatisticsRoute: typeof StatisticsRoute
  TemplatesRoute: typeof TemplatesRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  GalleryAlbumIdRoute: typeof GalleryAlbumIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery_/$albumId': {
      id: '/gallery_/$albumId'
      path: '/gallery/$albumId'
      fullPath: '/gallery/$albumId'
      preLoaderRoute: typeof GalleryAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  HabitsRoute: HabitsRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  StatisticsRoute: StatisticsRoute,
  TemplatesRoute: TemplatesRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  GalleryAlbumIdRoute: GalleryAlbumIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
